// Next
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// Styles
import './globals.css'

// Components
import Providers from './providers'
import { Header } from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Providers>
					<div className='container mx-auto px-4 max-w-6xl'>
						<Header />
						{children}
					</div>
				</Providers>
			</body>
		</html>
	)
}
